# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 14:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desgn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=8)),
                ('field', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_pic', models.ImageField(default='/pro_pic.png', upload_to='')),
                ('phone_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('room_no', models.CharField(max_length=10)),
                ('visit_time', models.TimeField()),
                ('Research_Interests', models.TextField(default='', max_length=1000)),
                ('Biography', models.TextField(default='')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Dept')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Desgn')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Detail', models.TextField()),
                ('Start_year', models.DateField()),
                ('End_year', models.DateField()),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Detail', models.TextField()),
                ('Date', models.DateField()),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Detail', models.TextField()),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=8)),
                ('Detail', models.TextField()),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=150)),
                ('password', models.CharField(default='myIITapp', max_length=50)),
                ('Pro_pic', models.ImageField(default='/pro_pic.png', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor'),
        ),
        migrations.AddField(
            model_name='education',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Dept'),
        ),
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IITG.Professor'),
        ),
    ]
