# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IITG', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='Dept_name',
        ),
    ]
