# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IITG', '0003_remove_dept_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Dept_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
