# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IITG', '0004_dept_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Name',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='experience',
            name='Institution',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='end_Year',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_Year',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
