# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IITG', '0005_auto_20171128_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Title',
        ),
    ]
