# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IITG', '0006_remove_experience_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='End_year',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Start_year',
        ),
        migrations.AddField(
            model_name='projects',
            name='end_Year',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='start_Year',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_Year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_Year',
            field=models.CharField(max_length=10),
        ),
    ]
